const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
let rows=[],email='staff@example.test',released=0,notes={};
const props={ALLOWED_EMAILS:email};
const sheet={getMaxColumns:()=>48,insertColumnsAfter:()=>{},getLastRow:()=>rows.length,setFrozenRows:()=>{},getRange:(r,c,n=1,w=1)=>({getNote:()=>notes[r]||'',setNote:v=>notes[r]=v,getValues:()=>rows.slice(r-1,r-1+n).map(row=>Array.from({length:w},(_,i)=>row[c-1+i]===undefined?'':row[c-1+i])),setValues:vs=>vs.forEach((row,i)=>{rows[r-1+i] ||= [];row.forEach((v,j)=>rows[r-1+i][c-1+j]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v)}),setNumberFormat:()=>{}})};
const context=vm.createContext({Session:{getActiveUser:()=>({getEmail:()=>email})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k]})},SpreadsheetApp:{openById:id=>{assert.equal(id,'1DydK1q8PZELyk2gTFmtxxiUtgSz6EYxRncw1Ep7JDSg');return {getSheetByName:name=>name==='DATA'&&rows.length?sheet:null,insertSheet:name=>{assert.equal(name,'DATA');return sheet}}},flush:()=>{}},LockService:{getScriptLock:()=>({waitLock:()=>{},releaseLock:()=>released++})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(alg,text)=>crypto.createHash(alg).update(text).digest(),base64Encode:bytes=>Buffer.from(bytes).toString('base64')}});
vm.runInContext(fs.readFileSync(__dirname+'/Code.gs','utf8'),context);
context.accountSession_=()=>({role:"user"});context.maintenanceUser_=()=>context.googleUser_();
const input={surveyDate:'2026-10-08',wbs:'WBS-01',transformer:'TR001',pea:'00001',note:'=formula',latlong:'12.5683,99.9577',old_cab:2,new_cab:3};
assert.equal(context.listPatrol().length,0);
const expectedKeys=['old_bolt_8in','old_bolt_10in','old_bolt_12in','old_bolt_14in','old_bolt_16in','old_bolt_18in','old_bolt_แหวน','old_wire_สีฟ้า','old_wire_สีดำ','old_wire_2x6','old_wire_2x10','old_wire_25','old_wire_50','old_cab','new_bolt_8in','new_bolt_10in','new_bolt_12in','new_bolt_14in','new_bolt_16in','new_bolt_18in','new_bolt_แหวน','wood_20','wood_60','wood_120','new_wire_2x10','new_wire_50','new_cab'];
expectedKeys.forEach((key,i)=>{if(key!=='old_cab'&&key!=='new_cab')input[key]=i+10});
const id='request-test-123456';context.savePatrol(input,id);context.savePatrol(input,id);assert.equal(rows.length,2);
expectedKeys.forEach((key,i)=>assert.equal(rows[1][14+i],input[key],key));
const r=context.listPatrol()[0];assert.equal(r.pea,'00001');assert.equal(r.old_cab,2);assert.equal(r.new_cab,3);assert.equal(r.note,'=formula');assert.equal(r.latitude,'12.5683');assert.equal(r.longitude,'99.9577');assert.equal(rows[1].length,44);assert.equal(rows[0][0],'Record ID');assert.equal(rows[1][6],'00001');assert.equal(rows[1][27],2);assert.equal(rows[1][40],3);assert.equal(JSON.parse(notes[2]).recordedBy,email);
assert.throws(()=>context.savePatrol({...input,wbs:'changed'},id));
for(const change of [{surveyDate:'2026-02-30'},{old_cab:-1},{old_cab:NaN},{note:{}},{latlong:'100,20'},{latlong:',20'},{before:'data:image/jpeg;base64,YWJj'}])assert.throws(()=>context.savePatrol({...input,...change},'another-request-12345'));
assert.equal(rows.length,2);
rows[1][3]='edited-in-sheet';assert.equal(context.listPatrol()[0].wbs,'edited-in-sheet');
email='outside@example.test';assert.throws(()=>context.listPatrol());assert.throws(()=>context.savePatrol(input,id));email='';assert.throws(()=>context.listPatrol());email='staff@example.test';rows[0][0]='broken';assert.throws(()=>context.listPatrol());assert.ok(released>0);
console.log('PASS: DATA 44-column mapping, coordinates, edits read back, read/write, retry deduplication, leading-zero PEA, validation, missing photo folder and unauthorized access (Google APIs simulated)');
